version: "2.1"
services:
  nginx:
    image: dptablo/nextjs-13-boilerplate-nginx-dev
    container_name: nextjs-13-boilerplate-nginx-dev
    ports:
      - "8888:8080"
    depends_on:
      - pm2
  pm2:
    image: dptablo/nextjs-13-boilerplate-pm2-dev
    container_name: nextjs-13-boilerplate-pm2-dev
    ports:
      - "13333:13333"
    expose:
      - "13333"